name: gorbatovski_lab_2
description: Create GET request and check its status code with http.cat Start project localy with "flutter run -d chrome --web-renderer html"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  validators: ^3.0.0
  provider: ^6.0.2

  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true